### ISSUE TITLE
Github presence

### ISSUE THREAD

**Issue by randlet** [qatrackplus/qatrackplus#263]
**[Original report](https://bitbucket.org/tohccmedphys/qatrackplus/issue/263) by Former user (Bitbucket: [Former user](https://bitbucket.org/Former user), ).**

----------------------------------------

Would it be an idea to have an official QAtrack presence on Github starting with 3.0, which could pull together all the different development work on tests taking place on there? For example, if I were working on an image processing module that could be directly linked from the main Github page, allowing others to find it quickly and contribute. It could then be Officially vetted before gaining the QAtrack seal of approval?

This could also happen on bitbucket, although I feel that Github is probably more widely used.

Btw I really loath the google groups interface, if that were deprecated I wouldn't miss it :-)

**Comment by crcrewso** [comment]
Looks like you can close this one!!!

**Comment by randlet** [comment]
1 Down 72 to go :laughing:

**Comment by randlet** [comment]
@crcrewso I know people aren't in love with Google Groups, but I do like having a more general purpose email list that doesn't require people have a GitHub account to participate in.  What usage do you see for Discussions that isn't covered by the email list?  I'm not terribly opposed to the idea, just curious what the motivation is.

**Comment by crcrewso** [comment]
I see both as having advantages and disadvantages. The big one for discussions is that when an issue thread gets sidetracked it can get kicked over to discussion

**Comment by randlet** [comment]
OK, I'll enable it and we can see how it goes.
