### ISSUE TITLE
Change Test Instance Status to Test List Instance Status level

### ISSUE THREAD

**Issue by randlet** [qatrackplus/qatrackplus#524]
**[Original report](https://bitbucket.org/tohccmedphys/qatrackplus/issue/524) by Randle Taylor (Bitbucket: [randlet](https://bitbucket.org/randlet), GitHub: [randlet](https://github.com/randlet)).**

----------------------------------------

I don’t think I’ve encountered anyone who sets test instance statuses differently within a given test list instance during manual review \(it can obviously happen due to autoreview\). In many ways moving the “Status” of QC data to the TestListInstance makes more sense than having it on individual test instance basis. People typically want to review the entire test list instance at the same time.

This would be a major breaking change but I think it should be considered seriously. Some points:

* Moving Status to TestListInstance level would likely simplify some code
* Some queries would become more efficient
* The TLI.all\_reviewed column could be eliminated.
* AutoReview rules would move from the Test level to the TestList or UnitTestCollection level. The latter would allow setting different AutoReview rules for the same Test List on different units.
* Migration edge cases might be tricky:

    * For TLI’s where all TI's have the same status, setting the new TLI Status would be easy but if a TLI has TI’s with different statuses you would need to decide which status to apply to the TLI \(for example if some TI’s still required review, the TLI should also require review\).
    * Migrating the AutoReviewRules would need to happen at the same time and would have similar issues; if not all tests within a test list have the same ARR’s set, how do you decide what the AutoReviewRule should be? Could possibly just declare bankruptcy on that front and have people reconfigure ARR completely.
    
* Bulk review would be simpler
* More to come as I think of them…

‌

**Comment by randlet** [comment]
As part of this change, we can likely remove UnitTestInfo.assigned_to and UnitTestInfo.active as I don't believe either are used anymore.

**Comment by crcrewso** [comment]
I think this would be a great change! though possibly large enough to be considered a 4.0

**Comment by randlet** [comment]
This change has been implemented in 3.2.0.
