### ISSUE TITLE
QATrack+ Link to documentation points to old url

### ISSUE THREAD

**Issue by tbezo** [qatrackplus/qatrackplus#549]
Hi,
I upgraded my system from 0.3.0 to 0.3.1 and the Documentation link on the start page of my installation still points to 
https://docs.qatrackplus.com/en/3.1.0/user/guide.html which does not contain the latest documentation.

with kind regards
Thomas

**Comment by randlet** [comment]
Thanks for the report! I've added a redirect so that visiting that URL will redirect to https://docs.qatrackplus.com/en/stable/user/guide.html
