### ISSUE TITLE
add pyldap in requirements ?

### ISSUE THREAD

**Issue by tguiot** [qatrackplus/qatrackplus#565]
I upgraded from 0.3.0 to 3.1.0 recently and after everything went well, the app threw an error. the apache log was referring to "ldap name not defined".

I figured I had to install a python ldap library, so "pip install pyldap" solved it.

maybe this package should be part of the requirements ? (in the doc, or directly in the source code ?)

thanks
Thomas

**Comment by randlet** [comment]
Hi Thomas, it is in the documentation [here](https://docs.qatrackplus.com/en/stable/install/authentication_backends.html) but you're right it could probably be called out in other parts of the docs to make it more obvious.

**Comment by crcrewso** [comment]
current python requirement is python-ldap v3.3 3.4 does not install correctly
