### ISSUE TITLE
Boolean test initial state doesn't seem to behave as documented

### ISSUE THREAD

**Issue by jrenegar** [qatrackplus/qatrackplus#569]
When creating a Boolean test, and setting its value to False in the calculation procedure, its initial state is YES when performing the test. 

![boolean initial state](https://user-images.githubusercontent.com/19570708/127651463-67e4ef60-f1aa-4da4-81cc-566fd246eea7.PNG)
![initial state is YES](https://user-images.githubusercontent.com/19570708/127651464-5bc44b92-45eb-4cec-a121-3a2b268badfe.PNG)

**Comment by randlet** [comment]
This was actually fixed just a week ago! https://github.com/qatrackplus/qatrackplus/issues/567

For now use `av_monitor = 0`

**Comment by jrenegar** [comment]
Don't know how I missed that on my search. I'm a github newb. That's excellent, thanks!
