### ISSUE TITLE
Fault type codes should strip whitespace

### ISSUE THREAD

**Issue by randlet** [qatrackplus/qatrackplus#581]
A fault type of "ABC " should be considered the same as "ABC". Note, users still need to be able to enter spaces, since "ABC 123" is a valid fault code.

**Comment by crcrewso** [comment]
Should we just strip() all strings before processing them?

**Comment by randlet** [comment]
Maybe?  Not sure off the top of my head if there's anywhere that leading/trailing whitespace would be desirable.  Not sure how it would be enforced though. Not something I personally have much of a desire to implement globally.

**Comment by randlet** [comment]
Resolved by 7522402d4a8f77dab39b14d4eccdfa0710c78d79
