### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by peterg1t** [qatrackplus/qatrackplus#584]
Hi Randy,
I was trying to develop a script that processed some data in parallel and stumbled upon this error -> 
> `File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap return self._map_async(func,iterable,starmapstar, chunksize).get() _pickle.PicklingError: Can't pickle <function point_detect at 0x7f113319da60> attribute lookup point_detect on __main__ failed`
 I was wondering if there was support for multiprocessing in QATrack+ or am I doing something wrong?

Thanks,
Pedro

**Comment by randlet** [comment]
Python can only pickle functions defined at the top level of a module which is likely why it's failing in this case.  More details [here](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function) including a potential workaround using `pathos` and `dill` although those answers are from years ago and I have no idea if those modules are still maintained.

**Comment by randlet** [comment]
Sorry, didn't answer your actual question "I was wondering if there was support for multiprocessing in QATrack+ or am I doing something wrong?"

There is no explicit support for multiprocessing and I have never attempted it myself so not sure if it's possible or not within a normal calculation.
