### ISSUE TITLE
Error 500 when accessing /api/servicelog/serviceevents/

### ISSUE THREAD

**Issue by nsmela** [qatrackplus/qatrackplus#593]
Good day Everyone,

We're testing out an API to port over service logs from our old database to QA Track+. The major issue we're having is that we get an internal error 500 when trying to access /api/servicelog/serviceevents/

- this is done an internal test server, not a live server
- we have 7 service events
- we can access any other directory under /api/servicelog/ without issue. For example, we can access /api/servicelog/thirdparty/
- authorized user is a super user
- tested this issue with the test program, a browser, and a testing extension on a browser
- also occurs for:
- /api/faults/faults/ (we have 8 existing faults)
- /api/schema/
- /api/servicelog/serviceevents/1/ (Service Event 1 does exist)

**Comment by randlet** [comment]
Thanks for reporting!  I will take a look and fix this up shortly.

**Comment by nsmela** [comment]
Thanks.  Finally got access to the server and found this in the log:

> [08/Dec/2021 09:28:10] ERROR [django.request:222] Internal Server Error: /api/servicelog/serviceevents/
> Traceback (most recent call last):
>   File "C:\deploy\venvs\qatrack31\lib\site-packages\rest_framework\relations.py", line 399, in to_representation
>     url = self.get_url(value, self.view_name, request, format)
>   File "C:\deploy\venvs\qatrack31\lib\site-packages\rest_framework\relations.py", line 337, in get_url
>     return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
>   File "C:\deploy\venvs\qatrack31\lib\site-packages\rest_framework\reverse.py", line 47, in reverse
>     url = _reverse(viewname, args, kwargs, request, format, **extra)
>   File "C:\deploy\venvs\qatrack31\lib\site-packages\rest_framework\reverse.py", line 60, in _reverse
>     url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
>   File "C:\deploy\venvs\qatrack31\lib\site-packages\django\urls\base.py", line 90, in reverse
>     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
>   File "C:\deploy\venvs\qatrack31\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
>     raise NoReverseMatch(msg)
> django.urls.exceptions.NoReverseMatch: Reverse for 'serviceeventschedule-detail' not found. 'serviceeventschedule-detail' is not a valid view function or pattern name.

**Comment by nsmela** [comment]
While testing a new install of 3.1.0, this is what I encountered:

> > Results (124.95s):
> >     1039 passed
> >        2 failed
> >          - qatrack/service_log/tests/test_views.py:295 TestCreateServiceEvent.test_submit_valid
> >          - qatrack/service_log/tests/test_views.py:615 TestEditServiceEvent.test_edit_service_event_valid
> >        5 skipped
> >       32 deselected
> 
> ――――――――――――――――――――――――――――――――――――――― TestCreateServiceEvent.test_submit_valid ―――――――――――――――――――――――――――――――――――――――
> 
> self = <qatrack.service_log.tests.test_views.TestCreateServiceEvent testMethod=test_submit_valid>
> 
>     def test_submit_valid(self):
> 
>         st = sl_utils.create_service_type()
> 
>         user = User.objects.filter(groups=self.gl_1.group).first()
>         user.user_permissions.add(Permission.objects.get(codename='can_have_hours'))
> 
>         data = {
>             'datetime_service': format_datetime(timezone.now()),
>             'unit_field': self.u_1.id,
>             'unit_field_fake': self.u_1.id,
>             'service_area_field': self.usa_1.service_area.id,
>             'service_type': st.id,
>             'problem_description': 'uhhhhh ohhhh',
>             'work_description': 'stuff was done',
>             'safety_precautions': 'we were careful',
>             'qafollowup_notes': 'comment',
>             'service_event_related_field': [sl_utils.create_service_event(unit_service_area=self.usa_1).id],
>             'service_status': models.ServiceEventStatus.get_default().id,
>             'test_list_instance_initiated_by': self.tli_1_1.id,
>             'duration_service_time': '4321',
>             'duration_lost_time': '1234',
>             'initiated_utc_field': self.tli_1_1.unit_test_collection.id,
>             'group_linker_1': user.id,
> 
>             'hours-INITIAL_FORMS': 0,
>             'hours-MAX_NUM_FORMS': 1000,
>             'hours-TOTAL_FORMS': 1,
>             'hours-MIN_NUM_FORMS': 0,
>             'parts-INITIAL_FORMS': 0,
>             'parts-MAX_NUM_FORMS': 1000,
>             'parts-TOTAL_FORMS': 1,
>             'parts-MIN_NUM_FORMS': 0,
>             'rtsqa-INITIAL_FORMS': 0,
>             'rtsqa-MAX_NUM_FORMS': 1000,
>             'rtsqa-TOTAL_FORMS': 1,
>             'rtsqa-MIN_NUM_FORMS': 0,
> 
>             'hours-0-time': '100',
>             'hours-0-user_or_thirdparty': 'user-%s' % user.id,
>             'rtsqa-0-all_reviewed': self.tli_1_2.all_reviewed,
>             'rtsqa-0-unit_test_collection': self.tli_1_2.unit_test_collection.id,
>             'rtsqa-0-test_list_instance': self.tli_1_2.id,
>             'parts-0-quantity': 1,
>             'parts-0-part': self.part.id,
>             'parts-0-from_storage': self.part.storage.all().first().id
>         }
> 
>         se_count = models.ServiceEvent.objects.count()
>         response = self.client.post(self.url, data=data)
> 
> >       se_id = models.ServiceEvent.objects.filter(problem_description='uhhhhh ohhhh').first().id
> E       AttributeError: 'NoneType' object has no attribute 'id'
> 
> qatrack/service_log/tests/test_views.py:346: AttributeError
> 
> ―――――――――――――――――――――――――――――――――― TestEditServiceEvent.test_edit_service_event_valid ――――――――――――――――――――――――――――――――――
> 
> self = <qatrack.service_log.tests.test_views.TestEditServiceEvent testMethod=test_edit_service_event_valid>
> 
>     def test_edit_service_event_valid(self):
> 
>         response = self.client.get(self.url)
> 
>         data = self.data
> 
>         data['hours-TOTAL_FORMS'] = 1
>         data['parts-TOTAL_FORMS'] = 1
>         data['rtsqa-TOTAL_FORMS'] = 1
>         data['parts-0-part'] = self.part.id
>         data['parts-0-quantity'] = 1
>         data['hours-0-user_or_thirdparty'] = 'user-%s' % self.user.id
>         data['hours-0-time'] = '0030'
>         data['rtsqa-0-all_reviewed'] = self.tli_1_2.all_reviewed
>         data['rtsqa-0-unit_test_collection'] = self.tli_1_2.unit_test_collection.id
>         data['rtsqa-0-test_list_instance'] = self.tli_1_2.id
>         data['rtsqa-0-id'] = ''
> 
>         response = self.client.post(self.url, data=data)
> 
> >       self.assertEqual(response.status_code, 302)
> E       AssertionError: 200 != 302
> 
> qatrack/service_log/tests/test_views.py:635: AssertionError

Most likely unrelated, but I figured I should add them just in case.

**Comment by randlet** [comment]
There were missing API endpoints which was causing an issue with service events which were part of a schedule.  Fixed in version 3.2.0 by 18a719517d26
