### ISSUE TITLE
Bug? Service Log Action Items does not match Service Events Needing Review

### ISSUE THREAD

**Issue by nsmela** [qatrackplus/qatrackplus#596]
In the attached image, it shows that there are 8 action items. When you mouse over the menu, it shows there's actually 9 Service Events needing review. The 8 action items is wrong, it should list 9.

We have three different service event statuses that require review, but the issue doesn't seem related to that. It corrects itself when I change service event status, but it won't revert when I go back to the previous service event.

(If I see 8 when I should see 9, I can change a single service event status and it's fixed. Then I can change that service event status back to the original and it still says 9)

There's also some parsing fault in the tooltip popup over the service events, as seen in the image.

![image](https://user-images.githubusercontent.com/10816249/145605839-7237cb72-14f2-4499-a89a-d9a9a8d37aa5.png)

**Comment by randlet** [comment]
Hi @nsmela the tool tip at the top is the sum of service events needing review, incomplete return to service work, and return to service work requiring review which is probably why you're seeing that discrepancy.

I've fixed the tool tips in 84d33d71
