### ISSUE TITLE
New installation: service log tests do not pass

### ISSUE THREAD

**Issue by leducvin** [qatrackplus/qatrackplus#601]
Hi, with a clean installation (following https://docs.qatrackplus.com/en/stable/install/linux.html#), as recommended I ran tests, however there were two failures:

```
touch qatrack/local_settings.py
make test_simple
```

> FAILED qatrack/service_log/tests/test_views.py::TestCreateServiceEvent::test_submit_valid - AttributeError: 'NoneType' object has no attribute 'id'
> FAILED qatrack/service_log/tests/test_views.py::TestEditServiceEvent::test_edit_service_event_valid - AssertionError: 200 != 302
> 
> Results (88.82s):
>     1039 passed
>        2 failed
>          - qatrack/service_log/tests/test_views.py:295 TestCreateServiceEvent.test_submit_valid
>          - qatrack/service_log/tests/test_views.py:615 TestEditServiceEvent.test_edit_service_event_valid
>        5 skipped
>       32 deselected
> make: *** [Makefile:18: test_simple] Error 1

I'm on checked out tag v3.1.0 with python 3.9.

**Comment by randlet** [comment]
This is resolved in 3.1.1.
