### ISSUE TITLE
Zero-interval frequency leads to infinite loop in migration qa.0023_set_recurrences

### ISSUE THREAD

**Issue by leducvin** [qatrackplus/qatrackplus#603]
Hi, a user on my site created a zero-interval Frequency and named it Ad Hoc.

While this is not the intended way of assigning ad hoc test lists (leaving Frequency blank), v0.3.0.18 which we are using, allowed this object to be created.

This lead to what seems to be an infinite loop in the migration `qa.0023_set_recurrences` while upgrading to v3.1.0.

The form whould validate that the interval is > 0 to prevent such an error in the future. For some reason, this validation was also not made by django-recurrence upon creating a Rule object in said migration.

**Comment by randlet** [comment]
Thank you Vincent.  Some validation should get added for zero interval frequencies.
