### ISSUE TITLE
Inconsistent REST API fields when fetching objects vs fetching a single object

### ISSUE THREAD

**Issue by leducvin** [qatrackplus/qatrackplus#604]
Hi Randle,

I don't know if this was intentional, but I have come across some inconsistencies as to the fields that we get from API when fetching a list vs fetching a single object. Specifically:

**When fetching units, we get:**
```
['active',
 'date_acceptance',
 'install_date',
 'is_serviceable',
 'location',
 'name',
 'number',
 'serial_number',
 'site',
 'type',
 'url']
```
**When fetching a single unit:**
```
['active',
 'date_acceptance',
 'install_date',
 'is_serviceable',
 'location',
 'modalities',
 'name',
 'number',
 'serial_number',
 'site',
 'type',
 'url']
```
`Difference: {'modalities'}`

**When fetching users:**
`['email', 'first_name', 'groups', 'last_name', 'url', 'username']`

**When fetching a user:**
```
['date_joined',
 'email',
 'first_name',
 'groups',
 'last_name',
 'permissions',
 'url',
 'username']
```
`Difference: {'date_joined', 'permissions'}`

I haven't made an exhaustive search for all the models. I came across these because I was using them.

**Comment by randlet** [comment]
Yes there are some spots where the results are different between list and details views.  Some differences may be mistakes, some are intentional. For example permissions is left out of users list because it may generate many queries.

**Comment by randlet** [comment]
Also any inconsistencies can be filed as bugs, and can be dealt with on a case by case basis.

**Comment by leducvin** [comment]
Ok, thanks Randle. It makes sense to remove some properties if too many queries are made for a list. Yeah I can work around it.
