### ISSUE TITLE
javascript error on page /reports

### ISSUE THREAD

**Issue by leducvin** [qatrackplus/qatrackplus#607]
Hi, I get intermittent errors in Chrome (fine in Firefox) in the /reports page:

```
reports.js?v=3.1.0:654 Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at reports.js?v=3.1.0:654:50
    at dispatch (jquery.min.js?v=3.1.0:3:7537)
    at r.handle (jquery.min.js?v=3.1.0:3:5620)
    at Object.trigger (jquery.min.js?v=3.1.0:4:4818)
    at jquery.min.js?v=3.1.0:4:5328
    at Function.each (jquery.min.js?v=3.1.0:2:2861)
    at n.fn.init.each (jquery.min.js?v=3.1.0:2:845)
    at n.fn.init.trigger (jquery.min.js?v=3.1.0:4:5304)
    at HTMLDocument.<anonymous> (reports.js?v=3.1.0:676:12)
    at i (jquery.min.js?v=3.1.0:2:27151)
```

Which happens here:
```
    $(document).ready(function(){


        /* maintain preview & filter window size */
        $(window).resize(function(e){

->            var pt = $previewContainer.position().top;
```

When I reload the page, about 1 out of 2 times, I get this error. If I interpret this correctly, it looks like sometimes the code gets executed before the element with #preview-container is ready? I don't understand that as this is already in the $(document).ready callback.

I'm on Chromium: 99.0.4844.45.

**Comment by randlet** [comment]
Was not able to reproduce, but put in a check to return early if position is undefined for some reason.

**Comment by leducvin** [comment]
Well, to be honest I have noticed that I only see this when connecting to QATrack+ through VPN. When I work on premises, I am not seeing this. It is very strange, but probably due to some network issue?
