### ISSUE TITLE
QC tree not loading on homepage

### ISSUE THREAD

**Issue by leducvin** [qatrackplus/qatrackplus#608]
Hi, got another weird one for you... I wonder if it can be reproduced.

In Chrome, the QC Unit & Frequency Tree is not loading, unless I do one of these:

- Refresh with CTRL+F5
- Disable cache within Chrome
- Disable cache on the web server
- Set `DEBUG=True` instead of `DEBUG=False` in `local_settings.py`.

All these workarounds more or less effectively disable cache.

Here is what I see:
![image](https://user-images.githubusercontent.com/22982038/159020959-83bd5d48-f2e9-46a3-9ca9-bad17e1d528d.png)

I only see this in Chrome. In Firefox it works fine, with and without caching.

**Comment by randlet** [comment]
Fixed in 49c16ab008c
