### ISSUE TITLE
Text colour (color) in test list is blue for some reason?

### ISSUE THREAD

**Issue by StyraxBenzoin** [qatrackplus/qatrackplus#611]
Not sure why, but in one of my test lists, almost all the text colour is blue. It wasn't like that when it was first made but it randomly changed and has even persisted across the v3.1.0 upgrade. This is the only test list that does this.

![QAT+ Test List font colour blue](https://user-images.githubusercontent.com/66492803/162211784-f30310b5-6e14-4b19-993a-86dc18a327ed.jpg)

Any ideas?

**Comment by randlet** [comment]
@StyraxBenzoin I suspect your test list description has an unclosed html tag in it.

**Comment by StyraxBenzoin** [comment]
Yes, that's it! There was a missing closing </a> tag for a href in the test list description. Sorry! Thank you.
