### ISSUE TITLE
ProgrammingError (1146, "Table 'qatrackplus31.qatrack_cache_table' doesn't exist")

### ISSUE THREAD

**Issue by wangwendong-code** [qatrackplus/qatrackplus#621]
![image](https://user-images.githubusercontent.com/81695609/177071707-3a1024f8-1be6-4836-8098-0a9ec4121194.png)
When I try to build a development environment with https://github.com/qatrackplus/qatrackplus/tree/v3.1.0.1, the program reports an error, as shown in the figure

**Comment by randlet** [comment]
Hello. You need to create the cache table `python manage.py createcachetable` will do it.

**Comment by wangwendong-code** [comment]
Got it!
