### ISSUE TITLE
LANGUAGE_CODE

### ISSUE THREAD

**Issue by wangwendong-code** [qatrackplus/qatrackplus#622]
When I try to build a development environment with https://github.com/qatrackplus/qatrackplus/tree/v3.1.0.1, i change LANGUAGE_CODE from 'en-us' to 'zh-Hans',however,the program reports an error，as shown
![image](https://user-images.githubusercontent.com/81695609/178671996-78df7fa6-aa0e-4c9b-a26a-09d2801a1abc.png)
![image](https://user-images.githubusercontent.com/81695609/178672114-ceedbc6a-3c97-4466-bb4d-d4ce92f6a17d.png)
The test results cannot be submitted and the echart chart cannot be generated normally

**Comment by randlet** [comment]
Hi, 
There is currently no support for languages other than English, so experiencing some issues when the `LANGUAGE_CODE` setting is changed is not unexpected.   However, @leducvin et al have been working on adding French translations in the pull request here: https://github.com/qatrackplus/qatrackplus/pull/620 which I have merged into the [3.2.0_translations branch](https://github.com/qatrackplus/qatrackplus/tree/3.2.0_translations).  Once that work is released, further language support might be available.
