### ISSUE TITLE
gunicorn.errors.HaltServer

### ISSUE THREAD

**Issue by ThirumuruganE** [qatrackplus/qatrackplus#623]
While I start the server using `docker-compose up`, I am getting error that says "gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>" . I have attached screenshot of the error. It also says there is no module named "qatack.local_setting". kindly help me to resolve this issue to up the server. 
Thanks
![Screenshot from 2022-07-15 08-47-12](https://user-images.githubusercontent.com/26036836/179145191-5319d714-9228-4984-b0cf-09f579386a70.png)

**Comment by randlet** [comment]
I don't really ever use Docker for QATrack+ but it looks to me like maybe need to create `local_settings.py`  in the `qatrack\` directory. Copying `deploy\postgres\local_settings.py` to the `qatrack\` folder might help.

**Comment by randlet** [comment]
Closing as I don't currently have time to debug.  Fix welcome if someone else has the time to investigate.
