### ISSUE TITLE
a bug when export  trend chart

### ISSUE THREAD

**Issue by wangwendong-code** [qatrackplus/qatrackplus#624]
https://github.com/qatrackplus/qatrackplus/blob/2636c9a8e4d6a4201b2382db59b8d415f29c1558/qatrack/qa/static/qa/js/qacharts.js#L2384
When I try to export the trend chart, I filter the review statuses under chart options on the right. However, it is invalid to filter the review statuses through the value of export_by_default of review statuses, regardless of  the value of export_by_default is true or false. When I annotate the above line of code, the handsome selector works normally. Sorry, I don't understand what the above line of code is about?

**Comment by randlet** [comment]
I think that line of code is setting some default statuses to include if no other status are selected, but there is no guarantee that statuses with ID=1 or ID=2 exist so it seems like a bug to me.
