### ISSUE TITLE
ask for a solution to a Localize need

### ISSUE THREAD

**Issue by wangwendong-code** [qatrackplus/qatrackplus#627]
In order to better use qatrack +, we want the main station to maintain the status now, while the django admin management uses our local language. However, once  I set  LANGUAGE_CODE = 'zh-hans' in  setting.py, the languages of both the main station and the django admin management will be switched, which will cause the master station to encounter the  problems(https://github.com/qatrackplus/qatrackplus/issues/622). So, is there any solution to meet our need?

**Comment by randlet** [comment]
There is no solution for internationalization at this point although it is something that is (very) slowly being worked towards.I will close this issue now since translation/internationalization is something being tracked in other tickets.
