### ISSUE TITLE
1024 character limit when saving dictionary

### ISSUE THREAD

**Issue by sama2689** [qatrackplus/qatrackplus#636]
I have a test aas a string composite called importT2, I am saving the file by dumping to json as follows to the macro import_T2_tb 
`import_T2_tb = json.dump(results)`

 This macro is a dictionary, which I later reference in several tests, for example
```
    T2 = json.loads(import_T2_tb)
    R_corr_6_10x = T2['10xR_corr_6']
```

All of this works just fine, the test runs, does everything I want, however, the software complains to me that I mustensure that 'Import T2 Images_TB' value has at most 1024 characters (it has 1064) and so I cannot submit. How do I get around this error? Is there a reason that QATrack+ has a character limit on dictionaries? Is there some workaround to get around this character limit?

Alternately, is there a way to save a variable in a test without it actually being cast to the macro that that test corresponds to?

I saw the thread about this [here ](https://github.com/qatrackplus/qatrackplus/issues/92)from many years ago, but I cannot access the linked comment anymore on bitbucket so am not able to look at the solution,

Any help much appreciated and thanks in advance

**Comment by randlet** [comment]
HI @sama2689 
What version of QATrack+ are you using?  Unless you are using a very old version of QATrack+ The string composite test stores its data in a Text field which should not have a character limit.
