### ISSUE TITLE
Text File Upload 

### ISSUE THREAD

**Issue by crcrewso** [qatrackplus/qatrackplus#637]
files ending in .log should try to open as txts instead of producing a 404 error. 
![image](https://user-images.githubusercontent.com/6089951/206757429-7f0d7cf2-d701-4397-badc-69fec9c7717a.png)

**Comment by randlet** [comment]
Hey Cody,

This isn't really a QATrack+ issue as it's IIS that is causing the 404 issue.  I think you need to add a mime type to IIS to force it to download as a file.

See https://bobcares.com/blog/how-to-add-mime-type-in-iis/

If this  is a trajectory log (?) you'd probably want to use application/octet-stream

**Comment by crcrewso** [comment]
> Hey Cody,
> 
> This isn't really a QATrack+ issue as it's IIS that is causing the 404 issue. I think you need to add a mime type to IIS to force it to download as a file.
> 
> See https://bobcares.com/blog/how-to-add-mime-type-in-iis/
> 
> If this is a trajectory log (?) you'd probably want to use application/octet-stream

Oh? Sorry for assuming. I'll try that. Thank you!
