### ISSUE TITLE
pandas uncommented in python3.10 branch

### ISSUE THREAD

**Issue by tbezo** [qatrackplus/qatrackplus#666]
Hi,

just upgraded ubuntu to version 22 using the python3.10 branch. After the ubuntu upgrade and recreation of the venv the only problem I came across was the missing pandas module. Why is is commented out in the requirements file?

Also I did the checkout before updating ubuntu and did not find anything wrong. Is it planned to update the requeirements for all coming QATrack+ releases?

regards
Thomas

**Comment by randlet** [comment]
I can't remember exactly what the python3.10 branch was used for...perhaps just testing things out and maybe pandas was giving me trouble, sorry not sure.  Yes requirements files typically get updated for releases.
