### ISSUE TITLE
Dynalog file analysis failed

### ISSUE THREAD

**Issue by wwdongcoder** [qatrackplus/qatrackplus#675]
Dear randlet
       When I use pylinac to analyze Dynalog, it shows that the analysis cannot be successful because Dynalog requires that the log file name must start with A and B, but the system renames the file when the file is uploaded. How can I deal with it so that the Dynalog can be analyzed successfully?

#This is my python script for the calculation process
import io
from pylinac import Dynalog
from matplotlib import pyplot as plt
dlog = Dynalog(BIN_FILE.path)
dynalog_analysis = {}
data = io.BytesIO()
dlog.publish_pdf(data)
UTILS.write_file("dynalog.pdf", data)
dlog.plot_summary()
UTILS.write_file("dynalog.png", plt.gca())

**Comment by wwdongcoder** [comment]
@randlet

**Comment by randlet** [comment]
I responded on the mailing list with an example of how you can do this.
