### ISSUE TITLE
Undefined override function?!

### ISSUE THREAD

**Issue by crcrewso** [qatrackplus/qatrackplus#679]
This could be an issue or this could be me. When investigating some odd behaviour I found that chrome dev tools showed an exception related to this call that coincided with when the page would become non-functional. I'm not strong with Javascript but when I remove this call everything appears to work. Is there a missing reference or is this call unnecessary?

https://github.com/qatrackplus/qatrackplus/blob/0c6f0a63d6bf70e7aec08c15143e50a5e510aa58/qatrack/service_log/static/service_log/js/sl_serviceevent.js#L89

**Comment by randlet** [comment]
AFAICT (I didn't write this code)  from https://github.com/qatrackplus/qatrackplus/blob/0c6f0a63d6bf70e7aec08c15143e50a5e510aa58/qatrack/qatrack_core/static/qatrack_core/js/base.js#L117  it is  just changing the way keyboard functionality works in the drop downs.  So removing the `overrideSelect2Keys` will change the keyboard behaviour but won't break anything else.  I've never seen an issue with this code pop up in our monitoring but if you post the traceback I can see whether there's an easy fix that can be applied.

**Comment by crcrewso** [comment]
I hope this stack trace is helpful. The behaviour is odd. The first time someone tries to enter a service event in Chrome or Edge in a new tab, this goes off without issue. Refreshes of this page or continuing to use the same tab to create new entries show this issue. 

``` JavaScript
sl_serviceevent.js?v=3.1.1.3:89 Uncaught TypeError: $(...).select2(...).overrideSelect2Keys is not a function
    at HTMLDocument.<anonymous> (sl_serviceevent.js?v=3.1.1.3:89:12)
    at i (jquery.min.js?v=3.1.1.3:2:27151)
    at Object.add [as done] (jquery.min.js?v=3.1.1.3:2:27450)
    at n.fn.ready (jquery.min.js?v=3.1.1.3:2:29515)
    at sl_serviceevent.js?v=3.1.1.3:5:17
    at Object.execCb (require.min.js?v=3.1.1.3:29:299)
    at da.check (require.min.js?v=3.1.1.3:18:50)
    at da.<anonymous> (require.min.js?v=3.1.1.3:22:264)
    at require.min.js?v=3.1.1.3:7:140
    at require.min.js?v=3.1.1.3:23:189
```

[sccqatrack-1723475041059.log](https://github.com/user-attachments/files/16588699/sccqatrack-1723475041059.log)

**Comment by lucserre** [comment]
Hi - I can confirm that this happens in our installation as well.  Refreshes of a page, or using same tab for more entries does that for us too.
Same overrideSelect2Keys in not a function errors.
The effect for us, is that the java isn't being run on the page, so we can't, for example, click on the date field and have a calendar appear to choose a date.
version 3.1.1.3
Thanks

**Comment by randlet** [comment]
Thanks for the traceback.  I couldn't reproduce it in dev mode, but could in production.  Fix is in master now.
